### ISSUE TITLE
rebuild for python=3.11

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/nctoolkit-feedstock#58]
Hi, it'd be nice to have a rebuild to support python=3.11 (provided CDO supports it, but it looks that way). I can trigger a PR if you guys OK with that, I always want to try and help with every issue I open :smiley: Incidentally, there is a bit of a bug - just a masked lack of support for python=3.11, but rendered as a bug, when importing the noarch nctoolkit in a Python=3.11 environment (that mamba deems installable - even if it's not)

```bash
(bgcval2-py11) valeriu@valeriu-PORTEGE-Z30-C:~/bgcval2$ python -V
Python 3.11.0
(bgcval2-py11) valeriu@valeriu-PORTEGE-Z30-C:~/bgcval2$ conda list nctoolkit
# packages in environment at /home/valeriu/miniconda3/envs/bgcval2-py11:
#
# Name                    Version                   Build  Channel
nctoolkit                 0.2.2              pyh32f6830_1    conda-forge
(bgcval2-py11) valeriu@valeriu-PORTEGE-Z30-C:~/bgcval2$ conda list cdo
# packages in environment at /home/valeriu/miniconda3/envs/bgcval2-py11:
#
# Name                    Version                   Build  Channel
cdo                       2.1.1                hb8d3726_1    conda-forge
(bgcval2-py11) valeriu@valeriu-PORTEGE-Z30-C:~/bgcval2$ python -c "import nctoolkit"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/valeriu/miniconda3/envs/bgcval2-py11/lib/python3.11/site-packages/nctoolkit/__init__.py", line 54, in <module>
    if valid(cdo_version) is False:
       ^^^^^^^^^^^^^^^^^^
  File "/home/valeriu/miniconda3/envs/bgcval2-py11/lib/python3.11/site-packages/nctoolkit/__init__.py", line 26, in valid
    where = [m.start() for m in re.finditer(sub, string)][n - 1]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

cheers :beer:

**Comment by robertjwilson** [comment]
Sounds like a good idea. Though, right now, this is not possible as one of nctoolkit's dependencies (datashader for plotting) relies on numba, which is still not available for Python 3.11 https://github.com/numba/numba/issues/8304.

It sounds like that's going to be resolved soon, so a 3.11 version of nctoolkit ought to be available once there is a working numba package for 3.11.

**Comment by valeriupredoi** [comment]
brilliant, cheers muchly @robertjwilson - please ping me when the time comes, so I can help in any way :+1: :beer:

**Comment by robertjwilson** [comment]
Thanks. I'll also set up a simple GitHub actions to alert me to when it can build for 3.11.

**Comment by robertjwilson** [comment]
I've got somewhere towards fixing this problem, @valeriupredoi. The main issue was that nctoolkit uses ncplot for plotting and it sometimes uses datashader, which relies on numba. 

However, I was able to drop the use of datashader for Python 3.11 in ncplot. Plots aren't as smooth or fast sometimes in the Python 3.11 version, but it works well enough.

I've just released version 0.2.9 of ncplot on pypi. Once it's on conda-forge and I've got the pinning right for datashader, it should be easy to get nctoolkit working on conda.

The pip version of nctoolkit should now work on Python 3.11, so long as you run `pip install ncplot==0.2.9` before hand.

I possibly need to create a new version of nctoolkit for conda-forge to build for Python 3.11, but that's no problem.

**Comment by valeriupredoi** [comment]
@robertjwilson that's awesome, cheers for pinging me about it! I think that once there's a new version on PyPI the conda regro-bot will pick that up and will automatically trigger a PR to the feedstock here with the new updated version; having said that, for me the bot's been slacking lately, so you may have to trigger one yourself, manually. About the optional dependency - that's a good move to exclude it - I've seen this being done very often (even big packages like Xarray do it) - if the code uses some optional/user-opt package, they tend to exclude it from the core dependencies. Even if that may result in an ImportError if the user forgets to install that package - makes the env lighter! :beer:

**Comment by robertjwilson** [comment]
I normally wait for the bot, though as you say it can be slow @valeriupredoi. I probably do need to switch some dependencies to optional because some (cartopy especially) keep causing problems.

**Comment by valeriupredoi** [comment]
cartopy and fiona are environment breakers, heavy backends with nasty wheels :grin:

**Comment by robertjwilson** [comment]
OK. A new version of ncplot is on conda-forge @valeriupredoi. But I've run into a problem. ncplot relies on geoviews. This was not a problem on pypi. But geoviews has datashader as a requirement on conda-forge, so right now you cannot install another other than a 4 year old version of geoviews in Python 3.11. They don't have this dependency on pypi, so this is possibly a redundant dependency that they have just not removed. 

I'll see if I can raise an issue over at geoviews.

**Comment by valeriupredoi** [comment]
@robertjwilson that's proper detective work, mate! I had a looksee myself, indeed `datashader` is preventing `geoviews` that's not 1.5 hence ancient, the problem with datashader is an old enemy: `numba`, see their [recipe](https://github.com/conda-forge/datashader-feedstock/blob/main/recipe/meta.yaml) - it depends on `numba`! Maybe it'd be worth asking on the `geoviews`'s feedstock if they can delete `datashader` from their requirements, if the PyPI package doesn't need it?

**Comment by robertjwilson** [comment]
They seem to be in the process of chaning things to make them compatible with Python 3.11, @valeriupredoi. I'll probably raise an issue to make your suggestion.

In the meantime I've realized a quick fix for this: dropping geoviews as a required dependency for ncplot. I've already done that on pypi, so you can do `pip install ncplot[complete]` if you want optional dependencies.

If I'm correct, conda-forge's bot should shortly re-render both ncplot and nctoolkit for Python 3.11, which should fix the Python 3.11 problem.

I'll need to tweak the nctoolkit recipe slightly so that it will still install the likes of geoviews for Python 3.10 and below, but that shouldn't be difficult.

**Comment by valeriupredoi** [comment]
that's awesome! I opened an issue on geoviews' feedstck https://github.com/conda-forge/geoviews-feedstock/issues/30 - apologies if I was a bit too eager, but have realized that `datashader` is just a recommended dep for them, so it'd be probably easier for them if they dropped it off the conda recipe anyway. Many thanks for your efforts @robertjwilson - great GH interaction with you, mate! :beer:

**Comment by robertjwilson** [comment]
nctoolkit was rebuilt for Python 3.11 overnight: https://github.com/conda-forge/nctoolkit-feedstock/pull/59#event-8645785413. I've just tested the conda 3.11 version locally and everything is fine.

I still need to do some pinning so that it picks up datashader for python 3.11, but that probably doesn't impact bgcval2. So I can probably close the issue now. Cheers @valeriupredoi

**Comment by valeriupredoi** [comment]
that is brilliant work, mate! All my tests are now green https://github.com/valeriupredoi/bgcval2/pull/88 and we now have full Python=3.11 support, very many thanks :beers: I'm keeping this open just in case you want it open for bookkeeping for the other pins, but job done for us, cheers :grin:

**Comment by robertjwilson** [comment]
I'll keep it open for now. I've just pushed a new version to pypi, but I'm waiting for the conda-forge bot to do a build. Once that's done I'll check if the new pinning works properly and close.

**Comment by valeriupredoi** [comment]
awesome, good luck! And ping me anytime you need some testing done by an external package or so, I owe you one :+1:

**Comment by robertjwilson** [comment]
Version 0.9.0 is now on conda-forge. I've just tested it to make sure datashader pinning is working for Python 3.11, and it's working fine. Closing the issue now. Cheers.

**Comment by valeriupredoi** [comment]
boss level @robertjwilson :medal_military:
